version: "2.1"
volumes:
  xserver:
services:
  xserver:
    image: bh.cr/balenalabs/xserver-aarch64
    restart: always
    privileged: true
    volumes:
      - "xserver:/tmp/.X11-unix"
  cctv-viewer:
    build: ./cctv-viewer
    restart: always
    devices:
      - /dev/dri
    group_add:
      - video
    volumes:
      - 'xserver:/tmp/.X11-unix'
  vnc:    
    build: ./vnc
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - 'xserver:/tmp/.X11-unix'
    environment:
      WEB_PORT: 80
      DISABLE_PASSWORDS: true
