version: "2.1"
networks:
  static:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/29
          gateway: 172.20.0.1
volumes:
  xserver:
services:
  xserver:
    build: ./xserver
    restart: always
    privileged: true
    ports:
      - "5900:5900"
    volumes:
      - "xserver:/tmp/.X11-unix"
    networks:
      static:
        ipv4_address: 172.20.0.2
  cctv-viewer:
    build: ./cctv-viewer
    restart: always
    devices:
      - /dev/dri
    group_add:
      - video
    volumes:
      - 'xserver:/tmp/.X11-unix'
    networks:
      static:
        ipv4_address: 172.20.0.3
  