version: "2.1"
networks:
  static:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/29
          gateway: 172.20.0.1
volumes:
  xserver:
services:
  xserver:
    image: bh.cr/balenalabs/xserver-aarch64
    restart: always
    privileged: true
    volumes:
      - "xserver:/tmp/.X11-unix"
    networks:
      static:
        ipv4_address: 172.20.0.2
  cctv-viewer:
    build: ./cctv-viewer
    restart: always
    devices:
      - /dev/dri
    group_add:
      - video
    volumes:
      - 'xserver:/tmp/.X11-unix'
    ports:
      - "5900:5900"
    networks:
      static:
        ipv4_address: 172.20.0.3
  vnc:    
    build: ./vnc
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - 'xserver:/tmp/.X11-unix'
    ports:
      - "80"
    environment:
      WEB_PORT: 80
      DISABLE_PASSWORDS: true
    labels:
      io.balena.features.supervisor-api: 1
    networks:
      static:
        ipv4_address: 172.20.0.4
